const realEstateData = [
    {
    name: "Woodland Villas",
    rooms: 2,
    bathrooms: 2,
    kitchens: 1,
    bhk: "2B-2H-K",
    sqft: "10,000 sqft",
    ratePerSqftInr: 4,
    amenities: ["Fresh Air", "Nature Oriented", "Elavator", "Parks Nearby", "Hospital Nearby", "Bicycle"],
    broker: "Aruna Dinesh Kumar",
        brokerContact: "1234567890",
        furnishing: "Fully Furnished",
    houseType: "Villa",
    image:""
},
{
    name: "Tea Estate",
    rooms: 2,
    bathrooms: 2,
    kitchens: 1,
    bhk: "2B-2H-K",
    sqft: "10,000 sqft",
    ratePerSqftInr: 4,
    amenities: ["Fresh Air", "Nature Oriented", "Elavator", "Parks Nearby", "Hospital Nearby", "Bicycle"],
    broker: "Aruna Dinesh Kumar",
    brokerContact: "1234567890",
    furnishing: "Fully Furnished",
    houseType: "Land",
    image:""
    },
    {
        name: "Emarald Office Space",
        rooms: 2,
        bathrooms: 2,
        kitchens: 1,
        bhk: "2B-2H-K",
        sqft: "10,000 sqft",
        ratePerSqftInr: 4,
        amenities: ["Fresh Air", "Nature Oriented", "Elavator", "Parks Nearby", "Hospital Nearby", "Bicycle"],
        broker: "Aruna Dinesh Kumar",
        brokerContact: "1234567890",
        houseType: "Office Space",
        furnishing: "Fully Furnished",
        image:""
    },
    {
        name: "Rangam Illam",
        rooms: 2,
        bathrooms: 2,
        kitchens: 1,
        bhk: "2B-2H-K",
        sqft: "10,000 sqft",
        ratePerSqftInr: 4,
        amenities: ["Fresh Air", "Nature Oriented", "Elavator", "Parks Nearby", "Hospital Nearby", "Bicycle"],
        broker: "Aruna Dinesh Kumar",
        brokerContact: "1234567890",
        houseType: "House",
        furnishing: "Fully Furnished",
        image:""
    },
    {
        name: "Kirloskar Office",
        rooms: 2,
        bathrooms: 2,
        kitchens: 1,
        bhk: "2B-2H-K",
        sqft: "10,000 sqft",
        ratePerSqftInr: 4,
        amenities: ["Fresh Air", "Nature Oriented", "Elavator", "Parks Nearby", "Hospital Nearby", "Bicycle"],
        broker: "Aruna Dinesh Kumar",
        brokerContact: "1234567890",
        houseType: "Office Space",
        furnishing: "Fully Furnished",
        image:""
    },
    {
        name: "Jaya House",
        rooms: 2,
        bathrooms: 2,
        kitchens: 1,
        bhk: "2B-2H-K",
        sqft: "10,000 sqft",
        ratePerSqftInr: 4,
        amenities: ["Fresh Air", "Nature Oriented", "Elavator", "Parks Nearby", "Hospital Nearby", "Bicycle"],
        broker: "Aruna Dinesh Kumar",
        brokerContact: "1234567890",
        houseType: "House",
        furnishing: "Fully Furnished",
        image:""
    }
] 